
# docker run --name=scribae-site -d -v ~/scribae-data/:/usr/lib/scribae/ -p 8088:4000 scribae

version: "3.3"
services:
  web:
    container_name: scribae_local
    volumes: 
      - ~/scribae-data/:/usr/lib/scribae-data/
    ports:
      - 8080:8080
    build:
      context: ./
      args:
        SCRIBAE_HOST: "0.0.0.0"
        SCRIBAE_PORT: 8080
        SCRIBAE_SRC: https://github.com/ng-galien/scribae.git
        SCRIBAE_URL: https://ng-galien.github.io
        SCRIBAE_BASEURL: /scribae-example
        SCRIBAE_GH_USER: ng-galien
        SCRIBAE_GH_REPO: https://github.com/ng-galien/scribae-sample.git


